# Generated by Django 5.1.4 on 2025-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=76432439, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
