# Generated by Django 5.1.4 on 2025-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('merchant', 'Merchant'), ('superuser', 'Superuser')], max_length=10),
        ),
    ]
