# Generated by Django 5.1.4 on 2024-12-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingsubcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='weddingsubcategory',
            name='categories',
            field=models.ManyToManyField(related_name='subcategories', to='weddings.weddingscategory'),
        ),
        migrations.AlterField(
            model_name='weddingsubcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='weddingsubcategory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
