# Generated by Django 5.1.4 on 2024-12-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_rename_name_weddingscategory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingsubcategory',
            old_name='name',
            new_name='title',
        ),
    ]
