# Generated by Django 5.1.4 on 2024-12-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_rename_name_weddingsubcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddings',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to='weddings.weddingscategory'),
        ),
        migrations.AlterField(
            model_name='weddings',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to='weddings.weddingsubcategory'),
        ),
    ]
