# Generated by Django 5.1.4 on 2024-12-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('weddings', '0002_remove_weddingsubcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='wedding_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_offerings', to='weddings.weddingscategory'),
        ),
    ]
