# Generated by Django 5.1.4 on 2025-01-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_responsive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
