# Generated by Django 5.1.4 on 2024-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stores', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='stores', to='products.centralizedproduct'),
        ),
    ]
