# Generated by Django 5.1.4 on 2025-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_hire', '0001_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rent_hire_categories',
            field=models.ManyToManyField(blank=True, related_name='store_rent_offerings', to='rent_hire.renthirecategory'),
        ),
    ]
