# Generated by Django 5.1.4 on 2025-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storeimage'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='wedding_category',
        ),
        migrations.AddField(
            model_name='store',
            name='wedding_categories',
            field=models.ManyToManyField(blank=True, related_name='store_wedding_offerings', to='weddings.weddingscategory'),
        ),
    ]
