# Generated by Django 5.1.4 on 2025-01-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
        ('store', '0006_remove_store_wedding_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='energy_categories',
            field=models.ManyToManyField(blank=True, related_name='store_energy_offerings', to='energy.energycategory'),
        ),
    ]
