# Generated by Django 5.1.4 on 2025-01-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_energy_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='energy_categories',
        ),
    ]
