# Generated by Django 5.1.4 on 2025-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energycategory',
            name='category',
        ),
        migrations.AddField(
            model_name='energycategory',
            name='categories',
            field=models.ManyToManyField(related_name='energy_categories', to='categories.category'),
        ),
    ]
